version: "3"
services:
 mysql:
  container_name: "web_mysql"
  image: "mysql:5.7.29"
  environment:
   MYSQL_ROOT_PASSWORD: "123456"
  volumes:
   - "./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d"
   - "./mysql/log:/var/log/mysql"
 redis:
  container_name: "web_redis"
  image: "redis:5.0.9"
  volumes:
   - "./redis/data:/data"
   - "./redis/redis.conf:/etc/redis.conf"
   - "./redis/log:/var/log/redis"
 fpm:
  container_name: "web_fpm"
  image: "php:7.2.30-fpm"
  volumes:
   - "./www:/var/www/html"
   - "./fpm/php-fpm.d:/usr/local/etc/php-fpm.d"
   - "./fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf"
   - "./fpm/log:/var/log/fpm"
  links:
   - "mysql"
   - "redis"
  depends_on:
   - "mysql"
   - "redis"
 nginx:
  container_name: "web_nginx"
  image: "nginx:1.18.0"
  volumes:
   - "./www:/var/www/html"
   - "./nginx/conf.d:/etc/nginx/conf.d"
   - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
   - "./nginx/log:/var/log/nginx"
  links:
   - "fpm"
  depends_on:
   - "fpm"
